trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      displayName: 'Install Terraform'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'terraform'
        backendServiceArm: 'DZDevelopment (9c65865e-cff3-4c1a-83dc-3ebc02089819)'
        backendAzureRmResourceGroupName: 'DevelopmentRG'
        backendAzureRmStorageAccountName: 'dzdevstorage'
        backendAzureRmContainerName: 'terraform'
        backendAzureRmKey: 'terraform-more.tfstate'
      displayName: 'Initialize Terraform'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'terraform'
        environmentServiceNameAzureRM: 'DZDevelopment(9c65865e-cff3-4c1a-83dc-3ebc02089819)'        
      displayName: 'Terraform Plan'
    
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'terraform'
        environmentServiceNameAzureRM: 'DZDevelopment (9c65865e-cff3-4c1a-83dc-3ebc02089819)'
      displayName: 'Terraform Apply'